### ISSUE TITLE
Not work vidplay? 

### ISSUE THREAD

**Issue by lavara123** [Ciarands/vidsrc-to-resolver#10]
Not work vidplay, maybe old keys

**Comment by Ciarands** [comment]
Working fine for me, was likely just a key mismatch, should only ever last a couple minutes, in future it will be a non-issue anyway.

https://github.com/Ciarands/vidsrc-to-resolver/assets/74070993/727e32d6-779d-4c2b-89df-1961e7faddba

Going to close this issue, if you have any errors that persist after the few minutes pass then please open another and provide the errors you're getting.

**Comment by lavara123** [comment]
> Working fine for me, was likely just a key mismatch, should only ever last a couple minutes, in future it will be a non-issue anyway.
> 
>  2024-01-09_18-39-41.mp4 
> Going to close this issue, if you have any errors that persist after the few minutes pass then please open another and provide the errors you're getting.


The issue was not working for a long time when I opened it, I think because the keys were not up to date
