### ISSUE TITLE
Base64 decode

### ISSUE THREAD

**Issue by gabinfinity** [Ciarands/vidsrc-to-resolver#13]
Sometimes the base64 decode function does not work, returning broken urls. Even using third-party tools this happens.

**Comment by Ciarands** [comment]
Cannot reproduce on Win 10 or Linux Mint, just double checking that you meant to open this issue here and not in https://github.com/Ciarands/vidsrc-me-resolver (similar names) where I have just fixed an issue with the base64 decoding.

**Comment by Ciarands** [comment]
Closing this issue due to no response, please reopen or create a new issue if you'd like to continue the discussion. Thanks!
