### ISSUE TITLE
Filemoon is broken

### ISSUE THREAD

**Issue by stunner999** [Ciarands/vidsrc-to-resolver#16]
![1](https://github.com/Ciarands/vidsrc-to-resolver/assets/129099102/afeb4603-f831-4023-809e-e7cbf31f3792)
but vidplay is fine.

**Comment by stl3** [comment]
I'm guessing the files hosted on filemoon have been removed as they are all 404 (at least every single one I've tried) using the api so in this case the program is working fine, but the files hosted on the server are 404 causing the error. It's been like this for the last few days but hopefully it gets resolved.
