### ISSUE TITLE
the keys changed?

### ISSUE THREAD

**Issue by no2drm** [Ciarands/vidsrc-to-resolver#17]
hi，

can you check if the decrypt key "8z5Ag5wgagfsOuhz" is changed. cannot get the url now.

TIA

**Comment by Ciarands** [comment]
Yeah, resolved in 6ee8cd5

**Comment by rahuloberai** [comment]
> Yeah, resolved in 6ee8cd5

Thanks now it's working. 
A quick question

Am trying to play m3u8 link in my custom player (jw player), previously it was working fine.
Now it's giving CORS error. Do you have any idea how i can fix this?

Thanks.

**Comment by rahuloberai** [comment]
Thanks buddy. 
I got it
