### ISSUE TITLE
Vidplay not returning any response

### ISSUE THREAD

**Issue by Aijazmakerb** [Ciarands/vidsrc-to-resolver#2]
After scraping from the vidplay for multiple times in a certain time period vidplay stops returning the url, i think vidplay is ip blocking me because after sometime like an hour, vidplay starts working again but then same thing happens again. Hope you understood what i am trying to say and will find a solution soon.

**Comment by Ciarands** [comment]
Yeah, from what I can tell theres a ratelimit in place, cant really do anything about this, you'll have to proxy requests if you intend to have multiple streams in a small timeframe.
