### ISSUE TITLE
fetch links with tmdb

### ISSUE THREAD

**Issue by Rhiannon99** [Ciarands/vidsrc-to-resolver#21]
hello please how i can fetch links with tmdb id like cool dev respo i just want filemoon embed links thank you

**Comment by Ciarands** [comment]
In this I am just scraping the tmdb website (see [here](https://github.com/Ciarands/vidsrc-to-resolver/blob/main/vidsrc.py#L99C5-L124C23)), this will likely not work at scale.
Check out the tmdb API, you can just put in some random info and get a read only key.

https://developer.themoviedb.org/docs/getting-started
